remote_theme: pages-themes/minima
plugins:
- jekyll-remote-theme 

# Setup
title:  "The impact of Beyond Toxics on Environmental Justice in Eugene"             
tagline:             
description:         
url:     http://eng470-s23.github.io          
baseurl:   /jamieoconnell/            
