remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme 

# Setup
title:  "The impact of Beyond Toxics on Environmental Justice in Eugene"             
tagline:             
description:         
url:     http://eng470-s23.github.io          
baseurl:   /jamieoconnell/  

github:
  zip_url: http://eng470-s23.github.io  
